language: php
dist: trusty
group: edge

php:
  - 8.0

before_script:
  - mkdir -p build/logs
  - mysql -e 'create database IF NOT EXISTS errorheromodule;' -uroot
  - mysql -u root errorheromodule < spec/Fixture/data/sql.sql
  - composer self-update
  - COMPOSER_PROCESS_TIMEOUT=5000 composer install --prefer-dist --ignore-platform-reqs
  - composer dump-autoload -o

script:
  - composer cs-check
  - bin/phpstan analyse src/ --level=max -c phpstan.neon
  - bin/rector process --dry-run
  - bin/kahlan --coverage=4 --reporter=verbose --clover=build/logs/clover.xml
  - bin/php-coveralls -v --exclude-no-stmt

notifications:
  email: false
